---
title: "Análisis de datos covid-19 en Costa Rica"
author: "Andy Valverde Ledezma"
date: '2022-05-11'
output:
  html_document:
    theme: readable    
    toc: true
    toc_depth: 5
    toc_float:
      collapsed: false
      smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Presentación
Este documento presenta gráficos generados a partir de los datos de COVID-19 en Costa Rica compartidos por el Ministerio de Salud en [https://geovision.uned.ac.cr/oges/](https://geovision.uned.ac.cr/oges/).

## Entradas  
### Datos generales de casos  
```{r}
covid <- read.csv(file="05_10_22_CSV_GENERAL.csv", sep = ";")
```

## Procesamiento  
### Opciones generales  
```{r}
options(scipen = 7)
```
### Curación de datos  
```{r}
covid$FECHA <- as.Date(covid$FECHA, format = "%d/%m/%Y")
```
## Salida

### Gráficos

#### Casos acumulados
##### Positivos
```{r}
plot(
  covid$FECHA,
  covid$positivos,
  type = "l",
  xaxt = "n",
  yaxt = "n",
  main = "Casos positivos acumulados de COVID en Costa Rica",
  xlab = "Fecha",
  ylab = "Positivos"
)

# Formato del eje X
axis(side = 1,
     covid$FECHA,
     tick = FALSE,
     format(covid$FECHA, "%m-%y"),
     cex.axis = .7)

# Formato del eje Y
axis(
  side = 2,
  covid$positivos,
  labels = TRUE,  
  at = seq(0, 1000000, by = 200000),
  cex.axis = .7
)
```

##### Fallecidos

```{r}
plot(
  covid$FECHA,
  covid$fallecidos,
  type = "l",
  xaxt = "n",
  yaxt = "n",
  main = "Casos fallecidos acumulados de COVID en Costa Rica",
  xlab = "Fecha",
  ylab = "Fallecidos"
)

# Formato del eje X
axis(side = 1,
     covid$FECHA,
     tick = FALSE,
     format(covid$FECHA, "%m-%y"),
     cex.axis = .7)

# Formato del eje Y
axis(
  side = 2,
  covid$fallecidos,
  labels = TRUE,  
  at = seq(0, 10000, by = 2000),
  cex.axis = .7
)
```

##### Otros

```{r}
plot(
  covid$FECHA,
  covid$positivos,
  type = "l",
  xaxt = "n",
  yaxt = "n",
  main = "Casos acumulados de COVID en Costa Rica",
  xlab = "Fecha",
  ylab = "Casos",
  col = "blue"
)
# Casos Activos
lines(covid$FECHA, covid$activos, col="red")
# Casos Recuperados
lines(covid$FECHA, covid$RECUPERADOS, col="green")
# Casos Fallecidos
lines(covid$FECHA, covid$fallecidos, col="black")



legend(
  x = "topleft",
  inset = 0.03,
  legend = c("Positivos", "Activos", "Recuperados", "Fallecidos"),
  col = c("blue", "red", "green", "black"),
  lty = 1,
  cex = 0.7)

axis(side = 1,
     covid$FECHA,
     tick = FALSE,
     format(covid$FECHA, "%m-%y"),
     cex.axis = .7)
# Formato de x
axis(
  side = 2,
  covid$positivos,
  labels = TRUE,  
  at = seq(0, 1000000, by = 200000),
  cex.axis = .7
)
```

